version: "2"
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-67
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true  
  reek:
    enabled: true  
  flog:
    enabled: true  
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
