#!/usr/bin/env bash
set -e

# Fix issue with livereload
cp /etc/hosts /etc/hosts.new
sed -i 's/::1\tlocalhost ip6-localhost ip6-loopback/::1 ip6-localhost ip6-loopback/' /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts

# Remove a potentially pre-existing server.pid for Rails.
rm -f /myapp/tmp/pids/server.pid

exec "$@"
